version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: argenis
      MYSQL_DATABASE: bdtemp
    ports:
      - 33060:3306
  app:
    container_name: proyecto_docker
    image: arge16/tingeso1
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/bdtemp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=argenis
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db