pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/arge16/mtings1']])
                dir("monolithic-webapp"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("monolithic-webapp"){
                    sh "mvn test"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("monolithic-webapp"){
                    sh "docker build -t arge16/tingeso1 ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("monolithic-webapp"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]){
                        sh "docker login -u arge16 -p ${dckpass}"
                        
                    }
                    sh "docker push arge16/tingeso1"
                    
                }
                
            }
        }
    }
    post{
        always{
            dir("monolithic-webapp"){
                sh "docker logout"
            }
        }
    }
}
